### ISSUE TITLE
Add additional content to the README

### ISSUE THREAD

**Issue by Ritnoel** [Roxie-32/writetechhub#4]
I will like to add an update to the README file

**Comment by Roxie-32** [comment]
Hi @Ritnoel , super excited to see this in action!

**Comment by Ritnoel** [comment]
Hello @Roxie-32, i just added some additional content to the README file.
Here is the link to the pull request https://github.com/Roxie-32/writetechhub/pull/5

**Comment by Roxie-32** [comment]
Awesome, Merged. Thank you for the good work
